// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0K7u23SKrN5gqdi1Rm3XGnFAGxDBijGo',
    appId: '1:848747041727:web:147f51bc8cf710f757070a',
    messagingSenderId: '848747041727',
    projectId: 'falldetection-af1e1',
    authDomain: 'falldetection-af1e1.firebaseapp.com',
    storageBucket: 'falldetection-af1e1.firebasestorage.app',
    measurementId: 'G-6QKWQTKRSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjp2Rvsjf_81h3XDl3v9pOeSS-ttgiezo',
    appId: '1:848747041727:android:df929d19783e4e9557070a',
    messagingSenderId: '848747041727',
    projectId: 'falldetection-af1e1',
    storageBucket: 'falldetection-af1e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbtTEHGE1K_0HnITR9S9BOVkcDpKaUKQ',
    appId: '1:848747041727:ios:e809bd003fde805257070a',
    messagingSenderId: '848747041727',
    projectId: 'falldetection-af1e1',
    storageBucket: 'falldetection-af1e1.firebasestorage.app',
    iosBundleId: 'com.example.fallDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIbtTEHGE1K_0HnITR9S9BOVkcDpKaUKQ',
    appId: '1:848747041727:ios:e809bd003fde805257070a',
    messagingSenderId: '848747041727',
    projectId: 'falldetection-af1e1',
    storageBucket: 'falldetection-af1e1.firebasestorage.app',
    iosBundleId: 'com.example.fallDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0K7u23SKrN5gqdi1Rm3XGnFAGxDBijGo',
    appId: '1:848747041727:web:c722b5a8d43f89eb57070a',
    messagingSenderId: '848747041727',
    projectId: 'falldetection-af1e1',
    authDomain: 'falldetection-af1e1.firebaseapp.com',
    storageBucket: 'falldetection-af1e1.firebasestorage.app',
    measurementId: 'G-VN141N67NL',
  );
}
